pod:
  host: devx1.symphony.com

agent:
  host: devx1.symphony.com

keyManager:
  host: devx1.symphony.com

bot:
  username: tibot
  privateKeyPath: /Users/thibault.pensec/local/conf/agent/privatekey.pem

app:
  appId: tibapp
  privateKeyPath: /Users/thibault.pensec/local/conf/agent/privatekey.pem

datafeed:
  version: v1
  retry:
    maxAttempts: 6
    initialIntervalMillis: 2000
    multiplier: 1.5
    maxIntervalMillis: 10000
