
bdk:
  host: devx1.symphony.com
  bot:
    username: tibot
    privateKeyPath: /Users/thibault.pensec/.symphony/privatekey.pem
  app:
    appId: tibapp
    privateKeyPath: /Users/thibault.pensec/.symphony/privatekey.pem

bdk-app:
  auth:
    enabled: true
    jwtCookie:
      enabled: true
      maxAge: 1d

logging:
  level:
    com.symphony: debug
