
bdk:
  host: acme.symphony.com
  bot:
    username: mybot
    privateKeyPath: ${user.home}/.symphony/keys/rsa-private-bot.pem

  app:
    appId: myapp
    privateKeyPath: ${user.home}/.symphony/keys/app_privatekey.pem

bdk-app:
  auth.enabled: true
  auth.jwtCookie:
    enabled: true
    expireIn: 43200
logging:
  level:
    com.symphony: debug

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
  port: 8443
spring.security.user.name: user
spring.security.user.password: password
