
bdk:
  host: devx1.symphony.com
  bot:
    username: fxbot-hong
    privateKeyPath: ${user.home}/.symphony/keys/rsa-private-bot.pem

  app:
    appId: testapp-hongle
    privateKeyPath: ${user.home}/.symphony/keys/app_privatekey.pem

bdk-app:
  auth:
    enabled: true
    jwtCookie:
      enabled: true
      expireIn: 43200

logging:
  level:
    com.symphony: debug
