domain: localhost.symphony.com

bdk:
  pod:
    scheme: https
    host: ${domain}
    port: 8443

  agent:
    scheme: https
    host: ${domain}
    port: 9443

  keyManager:
    scheme: https
    host: ${domain}
    port: 8443

  bot:
    username: tibot
    privateKeyPath: ${user.home}/local/conf/agent/privatekey.pem

logging:
  level:
    com.symphony: debug
