
bdk:
  host: devx1.symphony.com

  bot:
    username: postman-ecroze
    privateKey:
      path: /Users/elias.croze/.symphony/fbbot_privatekey.pkcs8

  datafeed:
    version: v2


logging:
  level:
    com.symphony: debug
