domain: devx1.symphony.com

bdk:
  pod:
    scheme: https
    host: ${domain}

  agent:
    scheme: https
    host: ${domain}

  keyManager:
    scheme: https
    host: ${domain}

  bot:
    username: fxbot-hong
    privateKeyPath: ${user.home}/dev/fxBot/rsa/rsa-private-fxBot.pem

logging:
  level:
    com.symphony: debug
