podUrl: https://devx1.symphony.com
agentUrl: https://devx1.symphony.com

username: 'tibot'
privateKeyPath: '/Users/thibault.pensec/local/conf/agent/privatekey.pem'

appId: 'tibapp'
appPrivateKeyPath: '/Users/thibault.pensec/local/conf/agent/privatekey.pem'
