title: BDK 2.0 for Java
description: Reference documentation for using the Symphony BDK to build bots
theme: just-the-docs
plugins:
  - jemoji
url: https://symphony-bdk-java.finos.org
color_scheme: symphony
aux_links:
  "BDK 2.0 on GitHub":
    - "//github.com/finos/symphony-bdk-java"
